<?php
$electronics = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Electronics' AND institution='$uni_id' AND state='1'";
$electronics_res = mysqli_query($conn,$electronics);
$row = mysqli_fetch_assoc($electronics_res);
$electronics_count = $row['num']; 
$property = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Property Sales & Rentals' AND institution='$uni_id' AND state='1'";
$property_res = mysqli_query($conn,$property);
$row = mysqli_fetch_assoc($property_res);
$property_count = $row['num'];
$furniture = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Home,Furniture & Appliances' AND institution='$uni_id' AND state='1'";
$h_res = mysqli_query($conn,$furniture);
$row = mysqli_fetch_assoc($h_res);
$furniture_count = $row['num'];
$fashion = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Fashion & Wears' AND institution='$uni_id' AND state='1'";
$f_res = mysqli_query($conn,$fashion);
$row = mysqli_fetch_assoc($f_res);
$f_count = $row['num'];
$mobile= "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Mobile Phones' AND institution='$uni_id' AND state='1'";;
$m_res = mysqli_query($conn,$mobile);
$row = mysqli_fetch_assoc($m_res);
$m_count = $row['num'];
$sports = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Sports & Arts' AND institution='$uni_id' AND state='1'";
$sports_res = mysqli_query($conn,$sports);
$row = mysqli_fetch_assoc($sports_res);
$sports_count = $row['num'];
$health = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Health & Beauty' AND institution='$uni_id' AND state='1'";
$health_res = mysqli_query($conn,$health);
$row = mysqli_fetch_assoc($health_res);
$health_count = $row['num'];
$v = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Cars & Automotives' AND institution='$uni_id' AND state='1'";
$v_res = mysqli_query($conn,$v);
$row = mysqli_fetch_assoc($v_res);
$v_count = $row['num'];
$food = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Food products' AND institution='$uni_id' AND state='1'";
$food_res = mysqli_query($conn,$food);
$row = mysqli_fetch_assoc($food_res);
$food_count = $row['num'];
$service = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Services' AND institution='$uni_id' AND state='1'";
$service_res = mysqli_query($conn,$service);
$row = mysqli_fetch_assoc($service_res);
$service_count = $row['num'];

$jobs = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Jobs' AND institution='$uni_id' AND state='1'";
$jobs_res = mysqli_query($conn,$jobs);
$row = mysqli_fetch_assoc($jobs_res);
$jobs_count = $row['num'];

$animals = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Animals & Pets' AND institution='$uni_id' AND state='1'";
$animals_res = mysqli_query($conn,$animals);
$row = mysqli_fetch_assoc($animals_res);
$animals_count = $row['num'];
$building = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Building Supplies' AND institution='$uni_id' AND state='1'";
$building_res = mysqli_query($conn,$building);
$row = mysqli_fetch_assoc($building_res);
$building_count = $row['num'];
$stationaries = "SELECT count(id) as num FROM tblproducts WHERE ProductCategory='Stationaries' AND institution='$uni_id' AND state='1'";
$stationaries_res = mysqli_query($conn,$stationaries);
$row = mysqli_fetch_assoc($stationaries_res);
$stationaries_count = $row['num'];
?>